source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

## Added Gems ##

## Add Bower to the project (package manager for JavaScript)
gem 'bower-rails'

## Add database_cleaner to clean databse after test are performed
gem 'database_cleaner'

## Add angular templates (need to precise version of sprockets)
gem "angular-rails-templates"
gem "sprockets", "~> 2.0"

## Use devise gem for authentification framework
gem 'devise'

## Use faker to create fake data
gem 'faker'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  ## Added Gems ##

  ## Add Rspec ruby testing framework for back end testing
  gem "rspec-rails", '~> 3.0'

  ## Add Poltergeist and Capybara (implicit) for end to end test

  # START_HIGHLIGHT
  gem 'poltergeist'
  # END_HIGHLIGHT

  ## Add jasmine front end testing framework using teaspoon
  ## (javascript test runner for Rails)
  gem 'teaspoon-jasmine'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  ## Added Gems ##
end
